        <div class="cont_inside">
			<div class="page-title">
          <h1>Expert Panel Of Doctors</h1>
        </div> 
            <div class="grids panel_docs">
                <ul>
                    <li id="1">
                        <a href="javascript:void(0);" data-target="1">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/Dr-Praveen-Dadireddy.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr.Praveen K Dadireddy</p>
                                <p>MRCS, FIORBS (GER)<br/>Consultant Breast Oncoplastic Surgeon</p>
                                <b>
                                    Oncoplastic Surgeon
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="2">
                        <a href="javascript:void(0);" data-target="2">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/Dr-Shabnam-Das-Kar.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. Shabnam Das Kar</p>
                                <p>MD, FAARFM</p>
                                <b>
                                    Fellow in Anti-Aging ,Regenerative & Functional Medicine.
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="3">
                        <a href="javascript:void(0)" data-target="3">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/naveen_talwar.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr Naveen Talwar</p>
                                <p>MBBS,MS(Ortho)</p>
                                <b>
                                    Orthopedics
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="4">
                        <a href="javascript:void(0);" data-target="4">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/bathina.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. Ravi N. Bathina</p>
                                <p>M.D.,F.A.C.C.</p>
                                <b>
                                    Cardiology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="5">
                        <a href="javascript:void(0);" data-target="1">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/Krishnam-Raju.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. P. Krishnam Raju</p>
                                <p>MD., DM (Cardiology)</p>
                                <b>
                                    Cardiology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="6">
                        <a href="javascript:void(0);" data-target="2">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/drsudha2.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. Sudha Sinha</p>
                                <p>Medical Oncologist</p>
                                <b>
                                    Oncology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="7">
                        <a href="javascript:void(0);" data-target="3">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/Raghu_Ram.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. P. Raghu Ram</p>
                                <p>MS, FRCS (London),<br/>FRCS (Edinburgh), FRCS (Glasgow), FRCS (Ireland)</p>
                                <b>
                                    Oncology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
                    <li id="8">
                        <a href="javascript:void(0);" data-target="4">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/drsrikanth.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. Vemula Sreekanth</p>
                                <p>MBBS, MD, DM</p>
                                <b>
                                    Neurology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
					<li id="9">
                        <a href="javascript:void(0)" data-target="4">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/msreddy.png');?>" />
                            </span>
                            <h5>
                                <p>Dr. M.S.Reddy</p>
                                <p>Consultant Psychiatrist</p>
                                <b>
                                    Neurology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
					<li id="10">
                        <a href="javascript:void(0);" data-target="4">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/YKSwapna.png');?>" />
                            </span>
                            <h5>
                                <p>Dr. Y K Swapna</p>
                                <p>Obstetrician, <br/> Gynaecologist & Laparoscopic Surgeon</p>
                                <b>
                                    Gynecology
                                </b>
                            </h5>
                            
                        </a>
                    </li>
					<li id="11">
                        <a href="javascript:void(0);" data-target="4">
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/Ysavithadevi.png');?>" />
                            </span>
                            <h5>
                                <p>Dr. Savitha Devi</p>
                                <p>Senior Consultant Obstetrician, <br/> Gynaecologist & Laparoscopic Surgeon</p>
                                <b>
                                    Gynecology
                                </b>
                            </h5>
                            
                        </a>
                    </li>

                </ul>
            </div>
            <div class="board_content trans_pt2s">
                <div class="board_content_in">
                    <div class="board_each">
                        <div class="left">
                                Role
                        </div>
                        <div class="right">
                                <p>CEO of Mapmygenome India, a genomics company whose vision is “Better health using technology”. </p>
                        </div>
                    </div>

                    <div class="board_each">
                        <div class="left">
                                About
                        </div>
                        <div class="right">
                                <p>She is a Co-Founder of Ocimum Biosolutions, which she led as the CEO (2000-March 2013). She is an alumnus of IIT Kharagpur and University of Illinois where she has two Post Graduate degrees in Physics and MIS.</p>
                        </div>
                    </div>

                    <div class="board_each">
                        <div class="left">
                                Awards and honors
                        </div>
                        <div class="right">
                                <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                Astia Life Science Innovators Award (2008)<br/>
                                25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                        </div>
                    </div>

                    <div class="board_each">
                        <div class="left">
                                Board positions
                        </div>
                        <div class="right">
                                <p>Current Board positions include Global Agenda Council on Genetics for WEF (Vice Chair), NIBMG (Governing Board Member), ABLE (Board Member), Action for India (Advisory Board Member), IvyCap Ventures (Board of Mentors), and KIIT (Advisory Board Member). Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member).</p>
                        </div>
                    </div>


                </div>
            </div>
        </div>
<div class="ovrly trans_pt4s"></div>

