        <div class="cont_inside">		
			<div class="page-title">
          <h1>Our Partners</h1>
        </div>
            <div class="grids partners">
                <ul>
                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner1.jpg');?>"/> 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner6.jpg');?>" /> 
                        </a>
                    </li>
                    
                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner7.jpg');?>" /> 
                        </a>
                    </li>

                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner8.jpg');?>" /> 
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner5.jpg');?>" /> 
                        </a>
                    </li>

                    
                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner2.jpg');?>" /> 
                        </a>
                    </li>


                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner9.jpg');?>" /> 
                        </a>
                    </li>
                    
                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner3.jpg');?>" /> 
                        </a>
                    </li>

                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner4.jpg');?>" /> 
                        </a>
                    </li>

                    

                    <!--<li>
                        <a href="javascript:void(0);">
                            <img src="<?php //echo $this->getSkinUrl('images/partners/partner10.jpg');?>" /> 
                        </a>
                    </li>-->

                    <li>
                        <a href="javascript:void(0);">
                            <img src="<?php echo $this->getSkinUrl('images/partners/partner11.jpg');?>" /> 
                        </a>
                    </li>

                    <li>
                        <a  style="cursor: pointer;" href="http://www.ocimumbio.com/" rel="nofollow" target="_blank">
                            <img src="<?php echo $this->getSkinUrl('images/partners/ocimum.png');?>" /> 
                        </a>
                    </li>

                    <!--<li>
                        <a href="javascript:void(0);">
                            <img src="<?php //echo $this->getSkinUrl('images/partners/partner12.jpg');?>" /> 
                        </a>
                    </li>-->

                    <!--<li>
                        <a href="javascript:void(0);">
                            <img src="<?php //echo $this->getSkinUrl('images/partners/partner13.jpg');?>" /> 
                        </a>
                    </li>-->

                </ul>
            </div>
            <div class="board_content trans_pt2s">
                <div class="board_content_in">
                    <div class="board_each">
                        <div class="left">
                                Role
                        </div>
                        <div class="right">
                                <p>CEO of Mapmygenome India, a genomics company whose vision is "Better health using technology". </p>
                        </div>
                    </div>

                    <div class="board_each">
                        <div class="left">
                                About
                        </div>
                        <div class="right">
                                <p>She is a Co-Founder of Ocimum Biosolutions, which she led as the CEO (2000-March 2013). She is an alumnus of IIT Kharagpur and University of Illinois where she has two Post Graduate degrees in Physics and MIS.</p>
                        </div>
                    </div>

                    <div class="board_each">
                        <div class="left">
                                Awards and honors
                        </div>
                        <div class="right">
                                <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                Astia Life Science Innovators Award (2008)<br/>
                                25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                        </div>
                    </div>

                    <div class="board_each">
                        <div class="left">
                                Board positions
                        </div>
                        <div class="right">
                                <p>Current Board positions include Global Agenda Council on Genetics for WEF (Vice Chair), NIBMG (Governing Board Member), ABLE (Board Member), Action for India (Advisory Board Member), IvyCap Ventures (Board of Mentors), and KIIT (Advisory Board Member). Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member).</p>
                        </div>
                    </div>


                </div>
            </div>
        </div>
<div class="ovrly trans_pt4s"></div>