    	 <!-- col left layout starts here-->
    <div class="main-container col1-layout">
               <div class="cont_inside">
			   <div class="page-title">
        <h1>About Mapmygenome</h1>
    </div>
            <div class="max_width">
                <div class="padd_50">
                    <!-- <h4>About Us</h4> -->
                    <p>Mapmygenome is a molecular diagnostics company to make people proactive about their health. They offer personalized health solutions based on genetic tests that help people to get to know about themselves. By combining genetic health profile and health history with genetic counseling, Mapmygenome provides actionable steps for individuals and their physicians towards a healthier life. Mapmygenome is focused on preventive health-care through healthy habits.<br/><br/>
Our teams at Hyderabad & Delhi comprise biotechnologists, statisticians, geneticists, bioinformaticians, and medical counselors. We have a technical expertise of 15+ years in the domains of genomics and big data. Our advisory panel has expert scientists and doctors. In order to enhance this innovative brand and to provide value-added services to customers, our highly-skilled research team works on cutting-edge technologies in various domains. 
                    </p>
                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">

                    <h4>We have a range of products and services spanning several verticals in healthcare.</h4>
                    <ul class="cmn_lists">
                        <li><p>Personal Genomics</p></li>
                        <li><p>Molecular Diagnostics</p></li>
                        <li><p>TB Diagnostic Kits</p></li>
                        <li><p>DNA Forensics</p></li>
                        <li><p>Brain Wellness</p></li>
                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>History</h4>
                    <p><br/></p>
                    <p>Founded in January 2013, Mapmygenome started as India’s pioneering Genomics Company with a vision to provide "Better Health for Indians using technology." Headquartered in Hyderabad, India, we connect to people across the globe with our business development executives, e-tailers, Brand Affiliates, and distributors. In March 2015, Mapmygenome raised a Pre Series A round of funding from multiple investors.</p>
                    

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">

                    <h4>Awards & Honors</h4>
                    <ul class="cmn_lists">
                        <li><p>In February 2015, Mapmygenome was awarded the Bio Excellence “Emerging Company of the Year” award by the Government of Karnataka.</p></li>
                        <li><p>In August 2015, Mapmygenome was nominated among the 5 Top Innovators for Jio Economic Times Startup Awards 2015 and CEO Anu Acharya was awarded the Women Ahead honour. </p></li>
                        <li><p>In September 2015, Mapmygenome made it to the SMARTCEO list of top 50 startups, for contribution to healthcare. </p></li>
                        <li><p>In September 2015, VCCircle honored Mapmygenome as Innovative Healthcare Startup of the year 2015.</p></li>
                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">

                    <h4>Watch The Video</h4><br/>
                    <div class="videoWrapper">
                        <iframe width="100%"  src="https://www.youtube.com/embed/2wNTxEfcOzQ" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- col left layout ends here-->
<div class="ovrly trans_pt4s"></div>