        <div class="cont_inside">		
			<div class="page-title">
          <h1>Logistics</h1>
        </div>
            <div class="max_width">
                <div class="padd_50">
                    <h4>Turnaround Time</h4>
                    <div class="cmn_table">
                        <div class="tr">
                            <div class="table_cell">
                                <p><b>Stage</b></p>
                            </div>
                            <div class="table_cell">
                                <p><b>Business Time</b></p>
                            </div>
                        </div>

                        <div class="tr">
                            <div class="table_cell">
                                <p>Delivery of kit after ordering the test</p>
                            </div>
                            <div class="table_cell">
                                <p>2-5 business days</p>
                            </div>
                        </div>

                        <div class="tr">
                            <div class="table_cell">
                                <p>Kit collection from your home after informing us</p>
                            </div>
                            <div class="table_cell">
                                <p>1-2 business days, depending on the time of calling</p>
                            </div>
                        </div>

                        <div class="tr">
                            <div class="table_cell">
                                <p>Report generation after receiving the sample</p>
                            </div>
                            <div class="table_cell">
                                <p>6-8 weeks</p>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <p>Logistics – our kits can be ordered from the privacy of your home. If required, you can opt for complete privacy wherein we will send the kit through discreet packaging.</p>
                    <br/><br/>
                    <h4>When you order for the test:</h4>
                    <ul class="cmn_lists">
                        <li><p>Our courier partners will deliver the kit to the address mentioned.</p></li>
                        <li><p>Sample collection can be done in the privacy of your home.</p></li>
                        <li><p>Mail us or call us and we will arrange for our courier partner to pick up the kit.</p></li>
                        <li><p>Once we receive the kit, we update the kit status in Biotracker™, our preferred Laboratory Information Management System. From here on, only the barcode on the kit is used for our internal purposes – be it processing of samples in the lab or analysis of data.</p></li>

                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>conditions</h4>
                    <ul class="cmn_lists">
                        <li><p>Before collecting saliva, read the instructions that come along with the kit.</p></li>
                        <li><p>The test kit comes with a sealing mechanism and instructions. Study the instructions and proceed with the sealing. 
Improper sealing can affect the quality of your DNA sample.</p></li>
                        <li><p>As soon as your saliva sample is ready, inform us so that we can arrange for a courier pick up. 
You can also send the kit to us through alternative courier services. Alternatively, you can drop in at our office to handover the kits.</p></li>
                        <li><p>Do not refrigerate the kits. The sample and ingredients should be in room temperature.</p></li>
                    </ul>

                </div>
            </div>
        </div>
