       <div class="cont_inside">
	   	<div class="page-title">
          <h1>Data Confidentiality</h1>
        </div>  
	   
            <div class="max_width">
                <div class="padd_50">
                    <!-- <h4>Data Confidentiality</h4> -->
                    <p>We use Biotracker™ by Ocimum Biosolutions to manage and track information at every stage of the process – from profile creation to sample collection, processing and reporting. This ensures compliance with GxP, US FDA’s 21 CFR Part 11, HIPAA, and caBIG® (bronze). The system not only allows privileged based access and audit trails for information storage, but also enables delinking of personal information.</p>
                </div>
            </div>
            <div class="max_width">
                <div class="padd_50">
                    <h4>conditions</h4>
                    <p class="p_top">It takes trust to build a relationship and we value your trust in us. At Mapmygenome, the protection and security of your information is our priority. To this end, we have enforced strict security measures to ensure confidentiality of personal information, samples, and reports.</p>

                    <ul class="cmn_lists">
                        <li><p>Profile creation: All the information you give us including details in the questionnaire are automatically captured and stored in Biotracker™. A barcode ID is generated for your profile that is used throughout the process.</p></li>

                        <li><p>Logistics: The sample collection package will be sent to you and our tie-ups with logistics service providers ensure that your sample is safely transported to our collection center.</p></li>

                        <li><p>Sample collection: A barcode is generated for your sample at the collection center to delink personal information and protect your privacy. The samples are then sent to our lab for further processing. We use your samples only for the analyses mentioned in the agreement. Biotracker™ tracks the chain of custody throughout.</p></li>

                        <li><p>Sample processing: Throughout the processing, personnel only have access to the barcode ID. Calculations are performed by the system based on your entries in the questionnaire and analysis of sample results. Results are directly parsed into Biotracker™ without any manual entry. This assures information accuracy and security.</p></li>

                        <li><p>Reporting: All reports are machine generated. Throughout the process, no personnel can access your report or tamper with it. Your reports are password protected to make sure no one can access them, except those people with whom you share the reports. Information backup: We periodically backup our system to prevent loss of information. The backup content is stored in a secure manner.</p></li>

                        <li><p>Information usage: With your consent, the delinked data including results from the questionnaire and genetic information generated from sample processing will be part of our research database. This will help you serve the Indian community better and contribute to health science.</p></li>

                        <p class="p_top">Our business is built on your trust and we guarantee confidentiality of your personal information.</p>
                    </ul>

                </div>
            </div>
        </div>

<div class="ovrly trans_pt4s"></div>
