    	 <!-- col left layout starts here-->
    <div class="main-container col1-layout">
       <div class="cont_inside">
    	   <div class="page-title">
                <h1>Awards & Honors</h1>
            </div>
            
             <div class="max_width">
                <div class="padd_50">
                    
                    <p>In August 2015, Mapmygenome was nominated among the 5 Top Innovators for Jio Economic Times Startup Awards 2015 and CEO. Award received in October 2015.</p>
                    <br/><br/>
                    <h4>Top 5 Innovators (Jio Economic Times Startup Awards)</h4>
                    <ul class="cmn_lists">
                        <li><a target="_blank" href="http://economictimes.indiatimes.com/small-biz/startups/economic-times-startup-awards-2015-indian-startups-will-transform-world-say-industry-experts/articleshow/49344555.cms"><span>Read</span> <p>Economic Times Startup Awards 2015: Indian startups will transform world, say industry experts</p></a></li>

                    </ul>

                    <br/><br/>
                    <h4>Women Ahead (Jio Economic Times Startup Awards)</h4>
                    <ul class="cmn_lists">
                        <li><a target="_blank" href="http://tech.economictimes.indiatimes.com/news/startups/et-startup-awards-anu-acharya-becomes-the-women-ahead/49325642"><span>Read</span> <p>ET startup awards: Anu Acharya becomes the "Women Ahead"</p></a></li>

                        <li><a target="_blank"  href="http://economictimes.indiatimes.com/et-now/daily/women-ahead-anu-acharya-mapmygenome/videoshow/49326377.cms"><span>Read</span> <p>Women Ahead: Anu Acharya, Mapmygenome</p></a></li>


                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <p>In October 2015, Mapmygenome was named in the Nasscom Emerge 50 2015 - League of 10 Profiles.</p>
                    <br/><br/>
                    <h4>NASSCOM Emerge 50 - League of 10</h4>
                    <ul class="cmn_lists">
                        <li><a target="_blank"  href="http://inc42.com/buzz/nasscom-emerge-10-award/"><span>Read</span> <p>Nasscom Announces Winners Of NASSCOM Emerge 10 Award</p></a></li>

                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    
                    <p>In October 2015, Mapmygenome CEO Anu Acharya received the FICCI FLO Women Achiever's award in the category Innovation through Technology</p>
                    <br/><br/>

                    <h4>Innovation Through Technology (FICCI FLO Women Acheivers' Awards)</h4><br/>
                    <p><img style="max-width:1200px;margin:0 auto;width:100%;" src="http://imgcdn.raagalahari.com/oct2015/local/ficci-women-achievers-night/ficci-women-achievers-night144.jpg" /></p>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <p>In September 2015, VCCircle honored Mapmygenome as Innovative Healthcare Startup of the year 2015.</p>
                    <br/><br/>

                    <h4>Innovative Healthcare Startup 2015 (VCCircle)</h4>
                    <ul class="cmn_lists">
                        <li><a target="_blank"  href="http://linkis.com/www.vccircle.com/new/BRvUY"><span>Read</span> <p>Meet winners of VCCircle Healthcare Awards 2015</p></a></li>

                    </ul>
                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    
                    <p>In September 2015, Mapmygenome made it to the SMARTCEO list of top 50 startups, for contribution to healthcare.</p>
                    <br/><br/>

                    <h4>Top 50 Startups (SmartCEO)</h4><br/>
                    <p><img style="max-width:600px;margin:0 auto;width:100%;" src="https://pbs.twimg.com/media/CN4opvGUwAA1wms.jpg" /></p>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    
                    <p>In February 2015, Mapmygenome was awarded the Bio Excellence "Emerging Company of the Year" award by the Government of Karnataka.</p>
                    <br/><br/>

                    <h4>Emerging Company of the Year (Bio Excellence - Govt. of Karnataka)</h4>	<br/>	 
                    <p><img style="max-width:600px;margin:0 auto;width:100%;" src="<?php echo $this->getSkinUrl('images/emerging_award.JPG');?>" /></p> 
                    <!-- <br/><br/>
                    <p><a href="http://linkis.com/www.vccircle.com/new/BRvUY">Meet winners of VCCircle Healthcare Awards 2015</a></p> -->

                </div>
            </div>

        </div>
    </div>
    <!-- col left layout ends here-->
<div class="ovrly trans_pt4s"></div>