        <div class="cont_inside">		
			<div class="page-title">
          <h1>Our Team</h1>
        </div>
            <div class="grids boards">
                <ul class="tabs">
                    <li id="1" class="tab-link" data-tab="tab-1" data-target="1">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/anu.jpg');?>" />
                            </span>
                            <h5>
                                <p>Ms. Anu Acharya</p>
                                <p>CEO, Mapmygenome <br/>Co-Founder, Ocimum Biosolutions</p>
                                <p>Know More</p>
                            </h5>

                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>

                    <li id="2" class="tab-link" data-tab="tab-2" data-target="2">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/naveen_talwar.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. Naveen Talwar</p>
                                <p>Chief Medical Officer</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>

                   <!-- <li id="3" class="tab-link" data-tab="tab-3" data-target="3">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php //echo $this->getSkinUrl('images/dp/bose.jpg');?>" />
                            </span>
                            <h5>
                                <p>Wing Commander (Dr.) MK Bose</p>
                                <p>Senior VP (Operations)</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>-->

                    <!--<li id="4" class="tab-link" data-tab="tab-4" data-target="4">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php //echo $this->getSkinUrl('images/dp/nita.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr Nita Sachan</p>
                                <p>VP – Business <br/>Development & Strategy</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>-->

                    <li id="5" class="tab-link" data-tab="tab-5" data-target="5">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/Jaishree.jpg');?>" />
                            </span>
                            <h5>
                                <p>Dr. Jaishree Srinivasan</p>
                                <p>VP <br/> Business Development</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>
					<li id="6" class="tab-link" data-tab="tab-6" data-target="6">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/geethanjali.jpg');?>" />
                            </span>
                            <h5>
                                <p>Geethanjali Tanikella</p>
                                <p>VP<br/> Corporate Communication</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>
					<!-- <li id="7" class="tab-link" data-tab="tab-7" data-target="7">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="images/dp/board.png" />
                            </span>
                            <h5>
                                <p>Dr Shravan K</p>
                                <p>Lab Manager</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li> -->
					<li id="8" class="tab-link" data-tab="tab-8" data-target="8">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/vijaya_shetty.jpg');?>" />
                            </span>
                            <h5>
                                <p>Vijaya Shetty</p>
                                <p>Manager, HR</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>

                </ul>
            </div>
            <div class="board_content trans_pt2s">
                <div class="board_content_in">
                    <!-- each tab -->
                    <div  id="tab-1" class="tab-content active"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>CEO of Mapmygenome India, a genomics company whose vision is "Better health using technology".</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>She is a Co-Founder of Ocimum Biosolutions, which she led as the CEO (2000-March 2013). She is an alumnus of IIT Kharagpur and University of Illinois where she has two Post Graduate degrees in Physics and MIS.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006).<br/></p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Global Agenda Council on Genetics for WEF (Vice Chair)<br/>
                                    NIBMG (Governing Board Member)<br/>
                                    ABLE (Board Member), Action for India (Advisory Board Member)<br/>
                                    IvyCap Ventures (Board of Mentors)<br/>
                                    KIIT (Advisory Board Member)<br/>
									Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member)<br/></p>
							</div>
                        </div>
                    </div>

                    <!-- each tab -->
                    <div  id="tab-2" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>Chief Medical Officer for Mapmygenome India, a genomics company whose vision is “Better health using technology”.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>He is an experienced Orthopaedic surgeon & Medical Advisor who understands Healthcare in India. He received his Bachelor's degree MBBS at UCMS college New Delhi and a Master's degree in ORTHOPEDICS at KGMC, Lucknow.</p>
                            </div>
                        </div>

                        <!--<div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                            </div>
                        </div>-->

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Board Member at United Way Charity (a leading US based charity worldwide), CANKIDS (a palliative paediatric cancer care chain) and THE GOLF FOUNDATION, INDIA.<br/>
									Dr. Talwar was Director Orthopedics with The Rockland Group of Hospitals and Medical Advisor to several healthcare companies like IMS, A & M AND Apex Medconnect to name a few.</p>
                            </div>
                        </div>
                    </div>

                    <!-- each tab -->
                    <div  id="tab-3" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>Senior VP (Operations) at Mapmygenome India, a genomics company whose vision is “Better health using technology”.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>Dr. MK Bose is an experienced and multifaceted health management professional with a career spanning over 33 years. Following a scintillating career in the Indian Air Force, he has worked extensively with the community in Public Health; in the field of leprosy, TB/HIV and blindness while being associated as Dy. CEO & Director of three Health Sector organizations. Dr. MK Bose specializes in the area of Telemedicine, Telecare and Telehealth.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Honorary PhD in Public Health, MA English Literature, MBA HR, and MBA Healthcare</p>
							</div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Serves as a Guest speaker at Singapore for the last five years<br/>
									Served as COO of two Super specialty hospitals</p>
                            </div>
                        </div>
                    </div>

                    <!-- each tab -->
                    <div  id="tab-4" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>VP – Business Development & Strategy at Mapmygenome India, a genomics company whose vision is “Better health using technology”.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>Dr. Nita has 17+ years of experience working at the interface of business and science. She has deep understanding of business strategy especially in technology intensive as well as service sectors. She completed her postdoctoral fellowship in Cardiology at the University of Texas Southwestern medical center (UTSW) at Dallas. Technology (IIT) and pursued her PhD in Molecular Biol. from University of Kentucky. She is also a certified licensing professional for Technology Commercialization and Intellectual Property by the University of California.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>She has been awarded the Women in Science and Medicine and was also nominated for the American Associate for Advancement of Sciences (AAAS).</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Previously worked at Indian School of Business (ISB) as Associate Director at the Business Incubator and the Biocon Cell for Innovation Management</p>
                            </div>
                        </div>
                    </div>

                    <!-- each tab -->
                    <div  id="tab-5" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>VP Business Development at Mapmygenome</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>She has a doctorate in Molecular Genetics, a post-doc in Molecular Virology  and over 10 years of work experience in the life science industry that span the spectrum of drug discovery and development, science publishing and healthcare across various geographies (US, Singapore, China and India).</p>
                            </div>
                        </div>

                        <!--<div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Current Board positions include Global Agenda Council on Genetics for WEF (Vice Chair), NIBMG (Governing Board Member), ABLE (Board Member), Action for India (Advisory Board Member), IvyCap Ventures (Board of Mentors), and KIIT (Advisory Board Member). Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member).</p>
                            </div>
                        </div>-->
                    </div>
					<div  id="tab-6" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>VP Corporate Communication at Mapmygenome</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>With her skills in publishing, single sourcing, and XML, she has automated the report generation process to ensure accurate conversion of data generated by bioinformaticians into a readable report. She is responsible for planning and execution of content publishing for marketing aids and collaterals, social media, press releases, ad hoc projects, and more. Geethanjali has 13+ years of experience in content development and publishing in various domains such as STM publishing, journalism, technical communication, and corporate communication. She has a Master’s Degree in Chemical Sciences and a Diploma in Web Content Development.</p>
                            </div>
                        </div>

                        <!--<div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Current Board positions include Global Agenda Council on Genetics for WEF (Vice Chair), NIBMG (Governing Board Member), ABLE (Board Member), Action for India (Advisory Board Member), IvyCap Ventures (Board of Mentors), and KIIT (Advisory Board Member). Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member).</p>
                            </div>
                        </div>-->
                    </div>
					<div  id="tab-7" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>Lab Manager at Mapmygenome</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>His core domains of expertise include developing new products using the Product Commercialization Process (PCP) - submitting product ideas, designing and testing ideas for feasibility, and developing feasible ideas into products. At Mapmygenome, he is responsible for several different technical projects in parallel. He oversees data analysis, interpretation and report generation. He coordinates project management, laboratory activities, and data analysis. He works with a cross-functional team to plan, implement and document formulation projects originating from broadly stated objectives and coordinate interactions with internal and external personnel on product development, scale up and application matters. He has 9+ years of experience working at different diagnostics services organizations. He completed his PhD from Osmania University and did his postdoctoral fellowship at Chang Gung University Taiwan.</p>
                            </div>
                        </div>

                        <!--<div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Current Board positions include Global Agenda Council on Genetics for WEF (Vice Chair), NIBMG (Governing Board Member), ABLE (Board Member), Action for India (Advisory Board Member), IvyCap Ventures (Board of Mentors), and KIIT (Advisory Board Member). Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member).</p>
                            </div>
                        </div>-->
                    </div>
					<div  id="tab-8" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>HR Manager at Mapmygenome</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>She plans, executes and controls Strategic HRM including Planning, Staffing, Developing, Monitoring, and Maintaining Resources. She is adept in creating an environment of teamwork, handling grievances, mediating workplace disputes and evaluating procedures & technology solutions. Vijaya is an out-of-the-box thinker committed towards growth of people within the organization. She has hands on experience in handling Competency Mapping, Discipline Management, Manpower Planning & Recruitment, Reward & Recognition System, Executive Development and Performance Management. Above all, Vijaya is an effective communicator with good interpersonal & relationship management skills and hands on experience in training and development of subordinates. Vijaya has a Master’s Diploma in Business Administration.</p>
                            </div>
                        </div>

                        <!--<div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Current Board positions include Global Agenda Council on Genetics for WEF (Vice Chair), NIBMG (Governing Board Member), ABLE (Board Member), Action for India (Advisory Board Member), IvyCap Ventures (Board of Mentors), and KIIT (Advisory Board Member). Past Board positions include Hyderabad chapter of the Entrepreneurs Organization (Past President) and CSIR (Governing Board Member).</p>
                            </div>
                        </div>-->
                    </div>

                </div>
            </div>
        </div>
<div class="ovrly trans_pt4s"></div>
<script type="text/javascript">

  jQuery(document).ready(function(){
    jQuery('.tabs li').click(function(){
        var tab_id = jQuery(this).attr('data-tab');

        jQuery('.tabs li').removeClass('active');
        jQuery('.tab-content').removeClass('active');

        jQuery(this).addClass('active');
        jQuery("#"+tab_id).addClass('active');

    })

  });

</script>
