       <div class="cont_inside">      
       <div class="page-title">
          <h1> FAQs</h1>
        </div>
            <div class="grids faqs">
                <ul>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s"></em>
                            <span class="num_head trans_pt2s">01</span>
                            <span class="ques">
                                <p><b>If you have questions, do not hesitate hit up the FAQ or just send us a message.</b><br/><br/>
                                <p>Our Genetic counselors can help you understand how our test’s can help you improve your lifestyle and improve your health.</p></p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Our Genetic counselors can help you understand how our test’s can help you improve your lifestyle and improve your health.</p>
                            </span>
                            <span class="trans_pt2s"></span>
                            
                        </a>
                    </li>

                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Predictive tests, Genomepatri, DNA, risk, diseases, traits, lifestyle tendencies, drug response, report, genetic code, medical condition, data, diet, exercise</em>
                            <span class="num_head trans_pt2s">01</span>
                            <span class="ques">
                                <p>Does a technician collect my buccal swab?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>No. You have to do it yourself by following the simple instructions presented within the kit</p>
                            </span>
                            <span class="trans_pt2s"></span>
                            
                        </a>
                    </li>

                    <li>
                        <a class="padd_50"> 
                            <em class="trans_pt2s">Report, genetic contribution, disease risk, drug toxicity, inherited, acquired, family, conditions, maternal history, complete health profile, genetic counseling, clinical relevance, physician</em>
                            <span class="num_head trans_pt2s">02</span>
                            <span class="ques">
                                <p>Is a blood sample better than a saliva sample?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Both work well for analysis, provided the sample collected is adequate. Buccal swabs need to be submitted as per the instructions within the kit. Blood samples require at least 2-3 ml. In case an inadequate sample is submitted, the client will be notified on priority.</p>
                            </span>
                            <span class="trans_pt2s"></span>
                            
                        </a>
                    </li>

                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Sample, altered health risks, report, updated, research, Genomepatri, new conditions</em>
                            <span class="num_head trans_pt2s">03</span>
                            <span class="ques">
                                <p>Where is my sample processed?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Every step of the sample processing happens in India, at our own full time laboratory by our own staff and trained personnel who are dedicated to Mapmygenome and its products.</p>
                            </span>
                            <span class="trans_pt2s"></span>
                            
                        </a>
                    </li>

                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Test, DNA, repeat analysis, periodical check, mutations, genetic material, altered risk, harmful, carcinogenic, resubmit, genotype, condition</em>
                            <span class="num_head trans_pt2s">04</span>
                            <span class="ques">
                                <p>Can I take a kit with me overseas and send the kit back to India after collection of the buccal swab sample without affecting the quality of the sample or losing the DNA?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Yes this is possible. After collection of the sample, it can be stored at ambient temperatures and does not require special packaging. Ensure the lid of the tube is screwed on tightly to avoid drying out of the swab.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Sample, processed, shipped, laboratory, Mapmygenome, India</em>
                            <span class="num_head trans_pt2s">05</span>
                            <span class="ques">
                                <p>What happens to my genomic data and how would you use it?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>We screen your genetic data for the presence or absence of variants or markers to calculate your risk thresholds as either ‘High’, ‘Medium’ or ‘Normal’. We have developed a robust algorithm which is used for risk estimation based on genotypes present in an individual’s DNA sample.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Medication, conditions, Genomepatri, disease, diabetes, tolerance, drugs, therapy, carrier status</em>
                            <span class="num_head trans_pt2s">06</span>
                            <span class="ques">
                                <p>What do you look for in my genome?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>We try to identify if your genome has any condition-associated mutations called Single Nucleotide Polymorphisms, also known as SNPs. If they are present, we try to identify what condition they are present in. </p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Age, Genomepatri, children, adults, prevent, disease, recommended</em>
                            <span class="num_head trans_pt2s">07</span>
                            <span class="ques">
                                <p>Do you have Indian specific data relating to SNPs?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>We take a very stringent approach to select our panel of SNPs. We only consider SNPs with proven association for any particular condition, replicated in many case-control studies, including multiple ethnicities. We include Indian-specific data where ever it is present and only if it passes our selection criteria. We are also building an ‘Indian-specific condition associated biomarker database’ through our research efforts, which will continuously feed our services.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Mapmygenome, patented, certifications, ISO certified</em>
                            <span class="num_head trans_pt2s">08</span>
                            <span class="ques">
                                <p>How extensive is the database I’m being mapped against and how representative is it of Indian population?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>We have built a database using over 14 years of our bioinformatics experience and by curating data from international journals and scientific literature. While we have tried to include as many conditions as possible to increase the value of the reports, we have focused on markers that have been validated and are suitable for the Indian population, especially for Type 2 diabetes, obesity, clopidogrel response and so on.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">09</span>
                            <span class="ques">
                                <p>If I take the test after say ten years, would my DNA result have changed, thereby requiring a repeat analysis? Is there a need for a periodical check?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Mutations or variations in genetic material are very less likely to develop over the years. From the time you were screened for certain markers, only if you have been subjected over a long period of time to drastic environmental changes or occupational/lifestyle habits that are harmful, you can wish to re-submit the sample and be analyzed again. Otherwise, the odds of genotype changing are low.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>


                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">10</span>
                            <span class="ques">
                                <p>Do I need to resubmit my sample if I want to check for altered health risks?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Your report is updated regularly in accordance to current research and databases registered worldwide. Once you sign up, you will receive free updates for a whole year, as and when we add new conditions or upgrade to a different database. A fresh sample is not required.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">11</span>
                            <span class="ques">
                                <p>If I am already on medication for certain conditions, why do I need Genomepatri?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>If you are already susceptible to a particular disease or are being treated for the same, you can understand your body’s tolerance and toxicity towards certain drugs, which affects therapy you are currently undergoing. Your report will also illuminate your carrier status for some diseases and thereby the probability of passing on the same to your children.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">12</span>
                            <span class="ques">
                                <p>What do LTR and ALTR mean?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>LTR is your life time risk for getting a particular disease. This notion is slightly confusing and we have summed it up as a multiple of average risk and explain the average risk in the content in detail. ALTR is the average life time risk in your population. These are numbers that have come from the prevalence ratios by WHO. If the ALTR is 8%, it means 8 out of 100 Indians have a risk of getting a particular disease.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">13</span>
                            <span class="ques">
                                <p>If I am marked as high risk, does it imply that I will get that disease?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>No, it doesn’t automatically imply that you will get the disease. For a disease to have a clinical manifestation, there are several other influencing factors such as familial history, lifestyle, clinical history and exposure to environmental factors.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">14</span>
                            <span class="ques">
                                <p>Are your products patented or FDA approved?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>We use the services of Ocimum Biosolutions that hold several patents in this space. We are also undergoing certifications like NABL and CE mark. The lab is already ISO certified.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">15</span>
                            <span class="ques">
                                <p>Does Mapmygenome have any certifications?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Yes, Mapmygenome uses the services of Ocimum Biosolutions. Ocimum Biosolutions has ISO 9001:2010 and ISO 13485:2012 certification. We are also undergoing NABL and ISO 15189 for medical labs and CE certification to enable sales to the EU.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <!--<li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">16</span>
                            <span class="ques">
                                <p>Why are the extra genes added if there is no relevance?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Markers that we don’t use today have some vague associations in small studies. As this field advances, that data will be markedly more interesting. As a result the large number of markers will be more relevant as the data set expands. We would then be able to come up with novel targets and also find smaller specific population specific associations which will be useful in the future.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">17</span>
                            <span class="ques">
                                <p>Why does company X test for more markers for a specific disease than Mapmygenome?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"One of the most important things is to ensure that we use statistically significant markers. That involves removing those mutations that do not follow our quality cut off criteria like size of study, P values, odd ratio etc. In order for a study to be relevant, we check on these parameters to ensure that there is a correct correlation with disease."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">18</span>
                            <span class="ques">
                                <p>"Has the Algorithm been proven to be better than others?"</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"The Snappy algorithm we use to process the genetic data is proprietary. The best confirmation of this is in the correlation of genotype to phenotype and matching it with their health records and family history. As the numbers increase, these can be validated with a higher accuracy. For specific diseases, we are at the moment working with some Pharma companies to be able to test a specific population with a specific disease. Numbers of 10,000 for a disease would be statistically significant but require large amounts of funding."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">19</span>
                            <span class="ques">
                                <p>Does mapmygenome have any certifications?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"Yes Mapmygenome uses the services of Ocimum Biosolutions. Ocimum has ISO 9001:2010 and ISO 13485:2012. Mapmygenome is also undergoing NABL and ISO 15189 for medical labs. Mapmygenome is also undergoing a CE certification to sell to the EU."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">20</span>
                            <span class="ques">
                                <p>Does mapmygenome have any IP protection?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"Mapmygenome has several trademarks filed and is planning on a patent for the Snappy Algorithm. Also because of the agreement with Ocimum, Mapmygenome has access to the 60 patents filed by Ocimum Biosolutions."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">21</span>
                            <span class="ques">
                                <p>What do Your LTR and ALTR mean?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"The ALTR is the average life time risk in your population. These are numbers that have come from the prevalence ratios by the WHO. If the ALTR is 8% then it means that 8 of 100 Indians would have a risk of getting this disease. When the ALTR is very low, the risk is very low in that population. Your LTR is your risk for getting the disease. This notation is indeed confusing and we have decided to make it a multiple of average risk and explain the average risk in the content in detail."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>


                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">22</span>
                            <span class="ques">
                                <p>"The genotypes don’t match some articles on the web, why?"</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"MMG uses Illumina’s Top Bot approach, as it is the most
standard form to ensure that the risks are accurately
calculated. This is a notation and can differ from DBSNP’s
notation."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">23</span>
                            <span class="ques">
                                <p>"How is Whole Genome Sequencing different from Genotyping?"</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"Whole genome sequencing or WGS is a method where your entire
genome is read alphabet-by-alphabet (ATGC), while genotyping is a
method to identify if there is a change in known and associated
location on your DNA. Genotyping is similar to WGS; however,
instead of looking at the entire genetic makeup, it is possible to look
at only certain meaningful locations in your genome. Moreover, WGS
is time consuming and expensive, whereas genotyping could be
managed at a fraction of that."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">24</span>
                            <span class="ques">
                                <p>What do you look for in my genome?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"We try to identify if your genome has any condition-associated
mutations called Single Nucleotide Polymorphisms (also known as
SNPs) and, if present, in what condition."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">25</span>
                            <span class="ques">
                                <p>Do you have Indian specific Data?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"We take a very stringent approach to select our panel of SNPs. We
only consider SNPs with proven association for any particular
condition, replicated in many case-control studies, including multiple
ethnicities. We include Indian-specific data wherever it is present and
only if it passes our selection criteria. We are also building an
‘Indian-specific condition associated biomarker database’ through our
research efforts, which will continuously feed our Mapmygenome.in
services."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">26</span>
                            <span class="ques">
                                <p>If I am marked as positive/negative or high risk. Does it imply I will get that disease?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"No, for a disease to have a clinical manifestation, there are several
other influencing factors such as familial history, lifestyle, clinical
history and exposure to other environmental factors."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">27</span>
                            <span class="ques">
                                <p>I have XX risk for Cardiovascular Disease. How did you estimate this?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>By screening various research articles, we have identified 13 SNPs that play a major role in Genetic Risk associated with Cardiovascular Diseases. For each of these SNPs, we have also collected information on their Genotypic Odds Ratios and frequencies. Using this information, we calculate Genetic Risk associated with genotypes of each SNP. A cumulative score is calculated across all the SNPs based on person’s genotypes. A person with risk genotype for many SNPs would have higher risk than the person with lesser number of risk genotypes. When you have 10 out of 13 markers, it means that you have risk genotype for 10 SNPs out of 13 SNPs that we have considered in our study. Consequently, you have 38% high risk for Cardiovascular Disease when compared to a person having no risk genotype (normal/control sample).</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">28</span>
                            <span class="ques">
                                <p>I would like to know if my autosomal DNA genotyped is available in your report.</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>In Genomepatri, we screen and report single nucleotide polymorphism (SNPs/markers) that contribute to high risk for a given health condition. These include: Autosomal regions,Sex-linked variants (X,Y chromosome snps),SNPs between genes,SNPs in coding regions of genes. Your report highlights only the markers which are significantly associated with the corresponding disease/trait/drug (in the tables provided), as these will increase your predisposition for the same, when compared to a control sample. If you wish to receive your complete profile/genotypes for the entire set of markers (raw data), we can send you the same.This will consist of autosomal DNA, as well as other data.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>





                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">29</span>
                            <span class="ques">
                                <p>Brainmap: Who will interpret the reports and give correct picture of his genetic predisposition and the counselling at your facility</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Post test counseling is included in the service, wherein a certified genetics expert goes through the report and health history, clinical indications etc and recommends appropriate measures - screening tests, diagnostics etc.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">30</span>
                            <span class="ques">
                                <p>The report sounds a little scary. What if I do not know how to deal or cope with the consequences?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Please understand that your report holds information pertaining to only the genetic contribution to overall disease risk/trait tendencies/drug toxicity. This could be inherited or acquired through your family or immediate relatives. For any condition, other factors like current eating, drinking and/or lifestyle, maternal history and daily routine/occupation influence your complete health profile. For example: A heavy smoker is more susceptible to lung cancer than someone who has a genetic predisposition to the same. We strongly recommend genetic counseling after you receive your report, to correctly understand the clinical relevance and check for follow-ups with your physician (if necessary).</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">31</span>
                            <span class="ques">
                                <p>What next after the report?</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>"The guidance by the genetic counselor helps in understanding
how to overcome a disease through diet and exercise. The
counselor also suggests how to get diagnostic and at what
frequency. We intend to send a followup report to the
consumer to arm them with this knowledge."</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>
                    <li>
                        <a class="padd_50">
                            <em class="trans_pt2s">Doctor’s prescription, medical recommendation, valuable information, better health, genetic risk, mitigation</em>
                            <span class="num_head trans_pt2s">32</span>
                            <span class="ques">
                                <p>"Is there a way to address health concerns after the test?"</p>
                            </span>
                            <span class="ans trans_pt4s padd_50">
                                <p>Mapmygenome has many partners for nutrition and fitness. Also Mapmygenome works with an expert panel of
doctors. Some of our partners have expressed interest in
supplying vitamins, medications but that needs evaluation at
this time.</p>
                            </span>
                            <span class="trans_pt2s"></span>

                        </a>
                    </li>-->
                </ul>
            </div>

        </div>
<div class="ovrly trans_pt4s"></div>


