<!-- col left layout starts here-->		 
<style type="text/css">
    .gsc-selected-option-container {
    width: 75px!important;
    max-width: 100%!important;
    
    
}
.gsc-webResult.gsc-result, .gsc-results .gsc-imageResult{
    border-color:#f1f1f1
}
.gcsc-branding{
    display: none
}
.gsc-results.gsc-webResult{
    border-bottom: none
}
.gsc-control-cse{
    border-color:transparent
}
.page-title{
    margin-right: 0
}
</style>
<div class="main-container col1-layout">
    <div class="cont_inside">
        <div class="page-title">
            <h1>Search Results</h1>
        </div>
        
        <gcse:searchresults></gcse:searchresults>

    </div>
</div>
