<?php

?>
<div class="page-title">
    <h1><?php echo $this->__('Kit Registration Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('kit/register/save') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Customer Information') ?></h2>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="gender" class="required"><em>*</em><?php echo $this->__('Gender') ?></label>
                <div class="input-box">
                <select class="validate-select" name="gender">
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
                </div>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
            <li>
                <label for="kit" class="required"><em>*</em><?php echo $this->__('Kit Barcode') ?></label>
                <div class="input-box">
                    <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="kit_barcode" id="kit_id" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kit Barcode')) ?>" class="input-text required-entry" />
                </div>
            </li>
            <li>
                <label for="kit" class="required"><em>*</em><?php echo $this->__('Kit Barcode') ?></label>
                <div class="input-box">
                    <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="kit_barcode" id="kit_id" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Kit Barcode')) ?>" class="input-text required-entry" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
