<div class="inside_bann inside_bann_prod inside_bann_small padd_30_50">
<!--<div class="prod_search">
            <div class="prod_search_in">
                <input class="inputNorm" placeholder="What are you looking for?" type="text">
                <a></a>
                <div class="trans_pt4s">
                    <span>
                        <p>Search</p>
                        <p>S Auto</p>
                        <p>S Fill content</p>
                        <p>Search</p>
                        <p>S Auto</p>
                        <p>S Fill content</p>
                    </span>
                </div>
            </div>
        </div>-->
	<div class="intro_grad trans_pt4s" data-color-start="rgb(89, 69, 174)" data-color-end="rgb(97, 218, 168)"></div>
</div>