   	   <div class="cont_inside">
	   	<div class="page-title">
          <h1>Board of directors</h1>
        </div>
            <div class="grids boards">
                <ul class="tabs">
                    <li id="1" class="tab-link" data-tab="tab-1" data-target="1">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/arjun.jpg');?>"/>
                            </span>
                            <h5>
                                <p>Mr. Arjun Malhotra</p>
                                <p>Co-Founder, <br/>HCL Technologies</p>
                                <p>Know More</p>
                            </h5>

                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>

                    <li id="2" class="tab-link" data-tab="tab-2" data-target="2">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/anula.jpg');?>"/>
                            </span>
                            <h5>
                                <p>Dr. Anula Jayasuriya MD, PhD</p>
                                <p>Co-founder and Managing Director, <br/>Evolvence India Life Science Fund (EILSF)</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>

                    <li id="3" class="tab-link" data-tab="tab-3" data-target="3">
                        <a>
                            <span class="dp trans_pt2s">
                                <image src="<?php echo $this->getSkinUrl('images/dp/anu.jpg');?>" />
                            </span>
                            <h5>
                                <p>Ms. Anu Acharya</p>
                                <p>Founder & CEO, <br/>Mapmygenome</p>
                                <p>Know More</p>
                            </h5>
                            <span class="trans_pt2s">
                                
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="board_content trans_pt2s">
                <div class="board_content_in">
                    <!-- each tab -->
                    <div  id="tab-1" class="tab-content active"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>Director on Board of Mapmygenome India</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>Mr. Malhotra graduated from Indian Institute of Technology (IIT), Kharagpur, with B. Tech. (Hons.) in Electronics & Electrical Communication Engineering and received the Dr. B.C. Roy Gold Medal. He also attended the Advanced Management Program at Harvard Business School.
He established the Prof. G.S. Sanyal School of Telecommunications at IIT Kharagpur through a personal endowment. He is also on the governing board of many institutes such as Myra School of Business and Entercoms and on the advisory board of organizations such as Ybrant Digital and NextGen eSolutions Private Limited.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Albert Einstein Technology Medal (Jerusalem Fund of Aish HaTorah, 2001)
Named Eminent Engineering Personality by The Institution of Engineers (India)
Life Fellow of IIT Kharagpur (2003)
Silicon Valley Entrepreneurs Award</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Co-founded the IT giant HCL Technologies and pioneered the group’s global expansion
CEO and Chairman of Board of Directors of Headstrong
Founder, CEO and Chairman of TechSpan which merged with Headstrong in October 2003
Member of the Board of Governors - IIT (Kharagpur) Foundation; the Indian School of Business, Hyderabad; Indian Institute of Management (IIM), Shillong; IIM, Udaipur; Indian Institute of Information Technology and Management, Gwalior; and the Indian Public Schools Society, Myra School of Business and Entercoms.
He established the Prof. G.S. Sanyal School of Telecommunications at IIT Kharagpur through a personal endowment.
Advisory board member at Ybrant Digital & NextGen eSolutions Private Limited</p>
							</div>
                        </div>
                    </div>

                    <!-- each tab -->
                    <div  id="tab-2" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>Director at Mapmygenome India. Co-founder and Managing Director, Invascent”.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>Dr. Jayasuriya has done her BA from Harvard summa cum laude, MD and PhD (in Microbiology and Molecular Genetics) from Harvard Medical School. She interned in Pediatrics at Boston Children’s Hospital. She also has an MBA with distinction from Harvard Business School and M. Phil. in pharmacology from the University of Cambridge, England.</p>
                            </div>
                        </div>

                        <!--<div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/>
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/>
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/>
                                    Astia Life Science Innovators Award (2008)<br/>
                                    25 Tech Titans under 35 (Red Herring, 2006). <br/></p>
                            </div>
                        </div>-->

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Co-founder and Managing Director of the Evolvence India Life Science Fund (EILSF)
Board Member at Health Care Global (Bangalore) and Lipomics Technologies (Sacramento, CA)
Non-profit board director for Astia, LPFI, Harvard Business School Health Industry Alum, and Gruter Institute for Law and Behavioural Research.
Earlier, was VP-Corporate Development at Genomics Collaborative Inc. and Vice President for Global Drug Development at Hoffman-La Roche. Dr. Jayasuriya also served as a partner with Skyline Ventures in Palo Alto and with TVM, a German-US venture capital firm in San Francisco.</p>
                            </div>
                        </div>
                    </div>

                    <!-- each tab -->
                    <div  id="tab-3" class="tab-content"> 
                        <div class="board_each">
                            <div class="left">
                                    Role
                            </div>
                            <div class="right">
                                    <p>CEO of Mapmygenome India, a genomics company whose vision is “Better health using technology”.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    About
                            </div>
                            <div class="right">
                                    <p>She is a Co-Founder of Ocimum Biosolutions, which she led as the CEO (2000-March 2013). She is an alumnus of IIT Kharagpur and University of Illinois where she has two Post Graduate degrees in Physics and MIS.</p>
                            </div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Awards and honors
                            </div>
                            <div class="right">
                                    <p>Member of Young Leaders Forum (British High Commission, 2013)<br/> 
                                    Young Global Leader (World Economic Forum (WEF) 2011)<br/> 
                                    Entrepreneur of the Year (Biospectrum, 2008)<br/> 
                                    Astia Life Science Innovators Award (2008)<br/> 
                                    25 Tech Titans under 35 (Red Herring, 2006).</p>
							</div>
                        </div>

                        <div class="board_each">
                            <div class="left">
                                    Board positions
                            </div>
                            <div class="right">
                                    <p>Global Agenda Council on Genetics for WEF (Vice Chair).
                                    NIBMG (Governing Board Member).<br/> 
                                    ABLE (Board Member), Action for India (Advisory Board Member).<br/> 
                                    IvyCap Ventures (Board of Mentors).<br/> 
                                    KIIT (Advisory Board Member).<br/> 
                                    Past Board positions include Hyderabad chapter of the Entrepreneurs.<br/> 
                                    Organization (Past President) and CSIR (Governing Board Member)</p>
                            </div>
                        </div>
                    </div>

                    

                </div>
            </div>
        </div>  

<div class="ovrly trans_pt4s"></div>
<script type="text/javascript">
  jQuery(document).ready(function(){
    jQuery('.tabs li').click(function(){
        var tab_id = jQuery(this).attr('data-tab');

        jQuery('.tabs li').removeClass('active');
        jQuery('.tab-content').removeClass('active');

        jQuery(this).addClass('active');
        jQuery("#"+tab_id).addClass('active');

    })
  });

</script>
