    	 <!-- col left layout starts here-->
    <div class="main-container col1-layout">
       <div class="cont_inside">
    	   <div class="page-title">
                <h1>Awards & Honors</h1>
            </div>
            
             <div class="max_width">
                <div class="padd_50">
                    <h4>Anu Acharya was awarded the Women Ahead honour</h4><br/>
                    <p>In August 2015, Mapmygenome was nominated among the 5 Top Innovators for Jio Economic Times Startup Awards 2015 and CEO. Award received in October 2015.</p>
                    <br/>
                    <ul class="cmn_lists">
                        <li><p><a target="_blank" href="http://economictimes.indiatimes.com/small-biz/startups/economic-times-startup-awards-2015-indian-startups-will-transform-world-say-industry-experts/articleshow/49344555.cms">Economic Times Startup Awards 2015: Indian startups will transform world, say industry experts</a></p></li>

                        <li><p><a target="_blank" href="http://tech.economictimes.indiatimes.com/news/startups/et-startup-awards-anu-acharya-becomes-the-women-ahead/49325642"> ET startup awards: Anu Acharya becomes the "Women Ahead"</a></p></li>

                        <li><p><a target="_blank"  href="http://economictimes.indiatimes.com/et-now/daily/women-ahead-anu-acharya-mapmygenome/videoshow/49326377.cms">Women Ahead: Anu Acharya, Mapmygenome</a></p></li>


                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>In October 2015, Mapmygenome was named in the Nasscom Emerge 50 2015 - League of 10 Profiles.</h4>
                    <br/>
                    <ul class="cmn_lists">
                        <li><p><a target="_blank"  href="http://inc42.com/buzz/nasscom-emerge-10-award/">Nasscom Announces Winners Of NASSCOM Emerge 10 Award</a></p></li>

                    </ul>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>FICCI FLO Women Achiever's Award</h4>
                    <br/>
                    <p>In October 2015, Mapmygenome CEO Anu Acharya received the FICCI FLO Women Achiever's award in the category Innovation through Technology</p>
                    <br/><br/>
                    <p><img style="max-width:1200px;margin:0 auto;width:100%;" src="http://imgcdn.raagalahari.com/oct2015/local/ficci-women-achievers-night/ficci-women-achievers-night144.jpg" /></p>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>Startup of the year</h4>
                    <br/>
                    <p>In September 2015, VCCircle honored Mapmygenome as Innovative Healthcare Startup of the year 2015.</p>
                    <br/>
                    
                    <ul class="cmn_lists">
                        <li><p><a target="_blank"  href="http://linkis.com/www.vccircle.com/new/BRvUY">Meet winners of VCCircle Healthcare Awards 2015</a></p></li>

                    </ul>
                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>SMARTCEO list of top 50 startups</h4>
                    <br/>
                    <p>In September 2015, Mapmygenome made it to the SMARTCEO list of top 50 startups, for contribution to healthcare.</p>
                    <br/><br/>
                    <p><img style="max-width:600px;margin:0 auto;width:100%;" src="https://pbs.twimg.com/media/CN4opvGUwAA1wms.jpg" /></p>

                </div>
            </div>

            <div class="max_width">
                <div class="padd_50">
                    <h4>Emerging Company of the Year</h4>
                    <br/>
                    <p>In February 2015, Mapmygenome was awarded the Bio Excellence "Emerging Company of the Year" award by the Government of Karnataka.</p>
					 <br/><br/>					 
                    <p><img style="max-width:600px;margin:0 auto;width:100%;" src="<?php echo $this->getSkinUrl('images/emerging_award.JPG');?>" /></p> 
                    <!-- <br/><br/>
                    <p><a href="http://linkis.com/www.vccircle.com/new/BRvUY">Meet winners of VCCircle Healthcare Awards 2015</a></p> -->

                </div>
            </div>

        </div>
    </div>
    <!-- col left layout ends here-->
<div class="ovrly trans_pt4s"></div>